# Generated by Django 2.1.7 on 2019-03-05 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='名称')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_price_item', to='goods.Price', verbose_name='价格')),
                ('shop', models.ManyToManyField(related_name='goods_shop_item', to='goods.Shop', verbose_name='商家')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
    ]
